name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
